language: python
cache:
    directories:
        - .tox

python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=docs
    - TOX_ENV=flake8
install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install tox
    - pip install coveralls
script:
    - tox -e $TOX_ENV
    - py.test

after_success:
    - coveralls
